### ISSUE TITLE
backtrace not available on alpine linux

### ISSUE THREAD

**Issue by ksedgwic** [ksedgwic/clboss#245]
reported by @king-11:
```
410.1 /usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-Signature.o):Signature.cpp:(.text._ZN4Util18BacktraceExceptionISt16invalid_argumentEC2IJRA23_KcEEEDpOT_[_ZN4Util18BacktraceExceptionISt16invalid_argumentEC5IJRA23_KcEEEDpOT_]+0x89): more undefined references to `backtrace' follow

RUN apk add --repository=https://dl-cdn.alpinelinux.org/alpine/v3.16/main/ libexecinfo-dev
RUN apk add elfutils-dev
before that the error was about missing header execinfo.h
```

**Comment by ksedgwic** [comment]
I think `libunwrap` will work

**Comment by king-11** [comment]
Actually I have tried all the available options at most of the implementations I have found related to backtrace they generally make it optional for alpine because of library incompatibility if that's an easier route to go with

**Comment by ksedgwic** [comment]
I was using libunwrap initially, and it worked.  After a bunch of exploration I decided it wasn't any better than backtrace, which I thought was omnipresent, so I switched back to backtrace.

I'd love to have a consistent solution that works averywhere, so maybe libunwrap is the one ... I don't think it is hard to try anyway (probably have the code in a git stash).

**Comment by king-11** [comment]
That would be great I can help in trying it out if you can push it to some branch.

**Comment by ksedgwic** [comment]
I pushed a draft: https://github.com/ZmnSCPxj/clboss/pull/249
- @king-11 Can you check if it works on Alpine?
- @chrisguida , @vincenzopalazzo Can you guys check if nix builds work for you?
- @vasild Can you check if FreeBSD builds?

**Comment by chrisguida** [comment]
Left a comment on #249

**Comment by king-11** [comment]
```bash
52.27 ../../Util/BacktraceException.hpp:5:10: fatal error: execinfo.h: No such file or directory
52.27     5 | #include <execinfo.h>
52.27       |          ^~~~~~~~~~~~
```

bare minimum clboss docker image
```dockerfile
FROM alphine:3.18

WORKDIR /build

RUN apk update && \
    apk add \
      git \
      autoconf-archive \
      automake \
      bind-tools \
      build-base \
      curl-dev \
      libev-dev \
      libtool \
      pkgconf \
      sqlite-dev

# new package for backtrace
RUN apk add libunwind-dev

ARG CLBOSS_GIT_HASH \
    CLBOSS_REPO
RUN git clone --recurse-submodules $CLBOSS_REPO clboss
RUN cd clboss && \
    git checkout $CLBOSS_GIT_HASH && \
    autoreconf -i && \
    ./configure --prefix=/usr && \
    make -j $(nproc) && \
    make -j $(nproc) install && \
    make clean
```

**Comment by king-11** [comment]
adding `libexecinfo-dev` reaches a litte farther but its not available with latest alpine images due to mentioned reasons [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/36722) and moreover it still fails

```
294.9 make[2]: *** [Makefile:3251: dev-boltz] Error 1
296.1 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-open_rpc_socket.o): in function `Util::BacktraceException<std::runtime_error>::format_backtrace[abi:cxx11]() const':
296.1 open_rpc_socket.cpp:(.text._ZNK4Util18BacktraceExceptionISt13runtime_errorE16format_backtraceB5cxx11Ev[_ZNK4Util18BacktraceExceptionISt13runtime_errorE16format_backtraceB5cxx11Ev]+0xf0): undefined reference to `backtrace_symbols'
296.1 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-Object.o): in function `Util::BacktraceException<std::invalid_argument>::format_backtrace[abi:cxx11]() const':
296.1 Object.cpp:(.text._ZNK4Util18BacktraceExceptionISt16invalid_argumentE16format_backtraceB5cxx11Ev[_ZNK4Util18BacktraceExceptionISt16invalid_argumentE16format_backtraceB5cxx11Ev]+0x10f): undefined reference to `backtrace_symbols'
296.2 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-runcmd.o): in function `Util::BacktraceException<Util::BacktraceException<std::runtime_error> >::format_backtrace[abi:cxx11]() const':
296.2 runcmd.cpp:(.text._ZNK4Util18BacktraceExceptionINS0_ISt13runtime_errorEEE16format_backtraceB5cxx11Ev[_ZNK4Util18BacktraceExceptionINS0_ISt13runtime_errorEEE16format_backtraceB5cxx11Ev]+0x11a): undefined reference to `backtrace_symbols'
296.2 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-NodeId.o): in function `Util::BacktraceException<std::range_error>::format_backtrace[abi:cxx11]() const':
296.2 NodeId.cpp:(.text._ZNK4Util18BacktraceExceptionISt11range_errorE16format_backtraceB5cxx11Ev[_ZNK4Util18BacktraceExceptionISt11range_errorE16format_backtraceB5cxx11Ev]+0xf0): undefined reference to `backtrace_symbols'
296.2 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libclboss.a(libclboss_la-PrivKey.o): in function `Util::BacktraceException<std::out_of_range>::format_backtrace[abi:cxx11]() const':
296.2 PrivKey.cpp:(.text._ZNK4Util18BacktraceExceptionISt12out_of_rangeE16format_backtraceB5cxx11Ev[_ZNK4Util18BacktraceExceptionISt12out_of_rangeE16format_backtraceB5cxx11Ev]+0x10f): undefined reference to `backtrace_symbols'
```

**Comment by vasild** [comment]
@king-11 that probably needs an extra `-lexecinfo`:

```sh
export LDFLAGS=-lexecinfo
./configure
make
```

**Comment by ksedgwic** [comment]
@king-11 Pls let me know if the additional `LDFLAGS=-lexecinfo` works for you (and I'll update the PR)

**Comment by king-11** [comment]
Thanks @vasild that did it, @ksedgwic the build succeeded.

The dependencies for alpine are:
- libunwind-dev
- libexecinfo-dev

**Comment by ksedgwic** [comment]
great!  I'll update the PR #249 

@vasild thanks for figuring this out!

**Comment by ksedgwic** [comment]
Fixed with #249
